title: Clean Blog
header-img: img/home-bg.jpg
email: "dklongley@postpal.com"
description: Just one of the modern website templates you can choose to use with your website
baseurl: /template-bootstrap-jekyl
url: "http://clean.postpal.com"
twitter_username: dklongley
github_username: dindinet
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      slug: ""
      tags: ""
      category: ""
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude:
  - less
  - node_modules
  - Gruntfile.js
  - package.json
  - README.md